#!/bin/bash

# Configuration
PREFIX=componette
COMPOSE_FILE=./docker-compose.yml
COMPOSE_SUB_FILE=./docker-compose.development.yml
VERSION=1.1

# Functions
usage() {
cat << EOF
Usage: ${0##*/} [-h]

Componette Docker Manager.

Version: $VERSION

Options:

  -h          Display this help and exit.

Commands:
  up          Create & create containers.
  fup         Force recreate containers.
  build       Build containers.
  reup        Build & force recreate containers.
  stop        Stop container.
  die         Destroy containers.
  logs        Display logs.
  exec        Exec command in container.
  go          Attach container.
EOF
}

call() {
	docker-compose -p $PREFIX -f $COMPOSE_FILE -f $COMPOSE_SUB_FILE $*
}

up() {
	call up -d
}

fup() {
	call up -d --force-recreate
}

build() {
	call build
}

reup() {
	build
	fup
}

stop() {
	call stop
}

destroy() {
	call stop
	call rm --all
}

logs() {
	call logs -f
}

fire() {
	call exec $1
}

go() {
	call exec $1 /bin/bash
}

# Main switch
case "$1" in
	up)
		up
		exit 0
		;;
	fup)
		fup
		exit 0
		;;
	build)
		build
		exit 0
		;;
	reup)
		reup
		exit 0
		;;
	stop)
		stop
		exit 0
		;;
	die)
		destroy
		exit 0
		;;
	logs)
		logs
		exit 0
		;;
	exec)
		fire
		exit 0
		;;
	go)
		go $2
		exit 0
		;;
	*)
		usage
		exit 1
		;;
esac
shift
